//
// Created by light on 17.12.17.
//

#ifndef EIGHT5_JAVA_COM_HARD_LIGHT_EIGHT5_MAINACTIVITY_ENCODE_H
#define EIGHT5_JAVA_COM_HARD_LIGHT_EIGHT5_MAINACTIVITY_ENCODE_H


class Java_com_hard_light_eight5_MainActivity_encode {

};


#endif //EIGHT5_JAVA_COM_HARD_LIGHT_EIGHT5_MAINACTIVITY_ENCODE_H
